### ISSUE TITLE
KeyError mpv

### ISSUE THREAD

**Issue by gotbletu** [McSinyx/comp#7]
trying the new version of comp but getting this error

`comp 'https://www.youtube.com/playlist?list=PLYosk6VjN4iYItFGfacO9HBRdeUcOP7OA'`
```
Traceback (most recent call last):
  File "/media/Suiton/Public/dotjutsu/virtualenv/.virtualenv/comp/bin/comp", line 346, in <module>
    mpv_args = dict(config['mpv'])
  File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'mpv
```

Python 3.6.4
pip 9.0.1

**Comment by McSinyx** [comment]
I'm sorry, my bad. I didn't test it to work w/o the config file. I think it works now.

**Comment by gotbletu** [comment]
ok works again
